"use client"

import { useLanguage } from "@/lib/language-context"
import { isEarlyPriceActive, retreatConfig, whatsappHref } from "@/lib/retreat-config"

export function Booking() {
  const { t } = useLanguage(); const c = t.booking as unknown as [string, string, string, string, string, string[], string, string, string, string, string, string]
  const early = isEarlyPriceActive()
  return <section className="mx-auto max-w-6xl px-6 pb-8"><div className="grid overflow-hidden border border-border bg-card lg:grid-cols-[.9fr_1.1fr]"><div className="bg-[hsl(25_45%_16%)] p-8 text-white md:p-12"><p className="text-xs tracking-[.2em] text-white/70">{c[0]}</p><p className="mt-10 font-serif text-5xl">{early ? retreatConfig.earlyPrice : retreatConfig.regularPrice} €</p>{early ? <><p className="mt-3 text-white/75">{c[1]}</p><p className="mt-2 text-white/75">{c[2]} {retreatConfig.regularPrice} €.</p></> : null}<p className="mt-10 text-sm font-medium tracking-[.16em]">{c[3]}</p><div className="mt-12 space-y-6"><div><h3 className="text-sm font-semibold tracking-[.14em]">{c[4]}</h3><ul className="mt-4 space-y-2 text-sm font-light leading-relaxed text-white/80">{c[5].map(item => <li key={item}>- {item}</li>)}</ul></div><div><h3 className="text-sm font-semibold tracking-[.14em]">{c[6]}</h3><p className="mt-3 whitespace-pre-line text-sm font-light leading-relaxed text-white/80">{c[7]}</p></div><div><h3 className="text-sm font-semibold tracking-[.14em]">{c[8]}</h3><p className="mt-3 whitespace-pre-line text-sm font-light leading-relaxed text-white/80">{c[9]}</p></div></div></div><div className="flex flex-col justify-center p-8 md:p-12"><h2 className="font-serif text-4xl font-medium md:text-5xl">БЕЗ МАСОК</h2><p className="mt-5 max-w-md whitespace-pre-line text-lg font-light leading-relaxed text-muted-foreground">{c[10]}</p><a href={whatsappHref()} className="mt-10 inline-flex w-fit rounded-full bg-primary px-7 py-4 text-base font-medium text-white">{t.nav}</a><a href={retreatConfig.instagramUrl} target="_blank" rel="noreferrer" className="mt-6 w-fit text-sm underline underline-offset-4 hover:text-primary">{c[11]}</a></div></div></section>
}
