const ru = {
  nav: "Хочу на Мадейру",
  hero: ["МАДЕЙРА · 5–10 НОЯБРЯ 2026", "БЕЗ МАСОК", "Пять дней, в которых тебе не нужно быть ни для кого.", "Океан. Приватная вилла. Маленькая группа.\nИ время только для себя.", "Всего 6 мест.", "Узнать подробности ↓"],
  featuresTitle: "ЧТО ТЕБЯ ЖДЁТ",
  features: [["МАДЕЙРА", "Океан, скалы, невероятные закаты и новые места."], ["ПРИВАТНАЯ ВИЛЛА", "Пять ночей. Бассейн, сад и вид на океан."], ["РАБОТА С СОБОЙ", "Понять себя глубже: чего тебе не хватает, чего ты хочешь и что мешает двигаться дальше."], ["ПРОФЕССИОНАЛЬНАЯ СЪЁМКА", "Два персональных видео о тебе, плюс фото и видео всего путешествия."], ["ВСЕГО 6 УЧАСТНИЦ", "Маленькая группа, где есть пространство и внимание для каждой."], ["ВСЁ ОРГАНИЗОВАНО", "Питание от личного повара, программа, организованные выезды, трансфер до локации съёмки и эксклюзивные подарки."]],
  concept: ["А какая ты, когда тебе ничего не нужно доказывать?", "Сильная. Правильная. Хорошая мама. Удобная. Успешная. Та, которая всегда справляется.", "Иногда мы так привыкаем к своим ролям и чужим ожиданиям, что перестаём замечать, где заканчиваются они и начинаемся мы.", "А чего на самом деле хочется мне?", "«Без масок» — пять дней, чтобы посмотреть на свою жизнь со стороны, разобраться, чего тебе не хватает, что тебя останавливает и что ты хочешь изменить.", "НЕ ПРОСТО ОТДОХНУТЬ.\nВЕРНУТЬСЯ С ПОНИМАНИЕМ, ЧТО ДЕЛАТЬ ДАЛЬШЕ.", "За эти дни мы будем разбираться в твоих желаниях, привычных сценариях и целях. Чтобы после Мадейры у тебя остались не только впечатления, но и конкретные решения для своей жизни."],
  gallery: ["КАК ЭТО БУДЕТ ОЩУЩАТЬСЯ", ["Начинать утро с прогулки и разминки у океана.", "Исследовать Мадейру.", "Говорить о том, на что обычно не хватает времени.", "Смеяться так, что болят щёки.", "Увидеть себя с другой стороны."], "Фото прошлого ретрита будет добавлено"],
  shoot: ["СЪЁМКА «БЕЗ МАСОК»", "В один из дней мы отправимся в одну из самых невероятных локаций Мадейры.", "В этот день ты сама решишь, какой хочешь себя показать. Нежной, дерзкой, сильной, уязвимой — любой. Без необходимости соответствовать чьим-то ожиданиям.", "Каждая участница получит два готовых персональных видео, а также фото и видео, снятые на протяжении всего ретрита.", "Фото Achadas da Cruz будет добавлено"],
  villa: ["НАШ ДОМ НА ПЯТЬ ДНЕЙ", "Приватная вилла только для нашей группы.\n\nБассейн. Сад. Вид на океан. И потрясающие закаты.", "Открыть галерею", "Фото"],
  hosts: [["Автор и ведущая ретрита", "Элия Дорлоу", "Коуч, тренер и официальный представитель Syucai Training Institute в Нидерландах.", "6 лет практики · Более 1000 клиентов", "Я работаю с мышлением, внутренними ограничениями, страхами и сомнениями. Помогаю разобраться, где ты сейчас, чего на самом деле хочешь и что мешает двигаться к своей цели.", "Для меня ретрит — это не только красивые места и яркие впечатления. Это глубокая внутренняя работа и конкретные действия, которые ты сможешь перенести в свою жизнь.", "Здесь будет место для честности с собой, ясности и собственных решений."], ["Видеограф ретрита", "Оля", "Профессиональный видеограф", "Оля умеет находить индивидуальный подход к каждой участнице, помогать раскрыться перед камерой и увидеть себя с новой стороны.", "Для неё важно не просто снять красивое видео, а создать результат, в котором ты понравишься самой себе.", "Твоя съёмка «Без масок» — возможность быть разной, настоящей и увидеть свою красоту без привычных ролей."]],
  booking: ["MADEIRA · 5–10 НОЯБРЯ", "При бронировании до 30 сентября включительно.", "С 1 октября —", "ВСЕГО 6 МЕСТ.", "В СТОИМОСТЬ ВХОДИТ:", ["Пять ночей на приватной вилле с бассейном.", "Питание от личного повара.", "Вся программа ретрита.", "Организованные выезды и трансфер до локации съёмки.", "Профессиональная съёмка.", "Два персональных видео, фото и видео ретрита.", "Эксклюзивные подарки."], "НЕ ВХОДИТ:", "Перелёт и трансфер до виллы.\nС организацией дороги поможем.", "БРОНИРОВАНИЕ:", "Бронь места — 300 €.\nВозможна оплата частями.", "Остались вопросы? Напиши мне — расскажу всё лично.", "Instagram →"],
  footer: ["БЕЗ МАСОК · MADEIRA 2026", "Элия Дорлоу", "Instagram: @elly_love_suzai"],
}

const en = {
  nav: "I want to go to Madeira",
  hero: ["MADEIRA · NOVEMBER 5–10, 2026", "WITHOUT MASKS", "Five days when you don't have to be anyone for anyone else.", "Ocean. A private villa. A small group.\nAnd time just for you.", "Only 6 places.", "Learn more ↓"],
  featuresTitle: "WHAT AWAITS YOU",
  features: [["MADEIRA", "Ocean, cliffs, incredible sunsets and new places."], ["A PRIVATE VILLA", "Five nights. A pool, a garden and an ocean view."], ["WORKING ON YOURSELF", "Understand yourself more deeply: what you lack, what you want and what is stopping you from moving forward."], ["PROFESSIONAL FILMING", "Two personal videos about you, plus photos and videos from the whole journey."], ["ONLY 6 PARTICIPANTS", "A small group with space and attention for everyone."], ["EVERYTHING IS ORGANISED", "Meals by a private chef, the programme, organised trips, transfer to the filming location and exclusive gifts."]],
  concept: ["Who are you when you have nothing to prove?", "Strong. Proper. A good mother. Convenient. Successful. The one who always copes.", "Sometimes we become so used to our roles and other people's expectations that we stop noticing where they end and we begin.", "What do I really want?", "“Without Masks” is five days to look at your life from the outside, understand what you are missing, what is holding you back and what you want to change.", "NOT JUST TO REST.\nTO RETURN KNOWING WHAT TO DO NEXT.", "During these days, we will explore your desires, familiar patterns and goals. So that after Madeira, you take home not only impressions, but concrete decisions for your life."],
  gallery: ["HOW IT WILL FEEL", ["Starting the morning with a walk and a warm-up by the ocean.", "Exploring Madeira.", "Talking about what there is usually no time for.", "Laughing until your cheeks hurt.", "Seeing yourself from another side."], "A photo from a past retreat will be added"],
  shoot: ["“WITHOUT MASKS” FILMING", "One day we will travel to one of Madeira's most incredible locations.", "That day, you choose how you want to show yourself: tender, bold, strong, vulnerable — anything. Without having to live up to anyone's expectations.", "Each participant will receive two finished personal videos, as well as photos and videos shot throughout the retreat.", "An Achadas da Cruz photo will be added"],
  villa: ["OUR HOME FOR FIVE DAYS", "A private villa exclusively for our group.\n\nA pool. A garden. An ocean view. And breathtaking sunsets.", "Open gallery", "Photos"],
  hosts: [["Author and retreat leader", "Elija Deurloo", "Coach, trainer and official representative of Syucai Training Institute in the Netherlands.", "6 years of practice · More than 1,000 clients", "I work with mindset, inner limitations, fears and doubts. I help you understand where you are now, what you truly want and what prevents you from moving towards your goal.", "For me, a retreat is not only beautiful places and vivid impressions. It is deep inner work and concrete actions you can bring into your life.", "There will be room for honesty with yourself, clarity and your own decisions here."], ["Retreat videographer", "Olya", "Professional videographer", "Olya knows how to find an individual approach to every participant, help her open up in front of the camera and see herself in a new way.", "For her, it is important not simply to make a beautiful video, but to create a result that you will like yourself in.", "Your “Without Masks” shoot is an opportunity to be different, real and to see your beauty beyond familiar roles."]],
  booking: ["MADEIRA · NOVEMBER 5–10", "For bookings by and including September 30.", "From October 1 —", "ONLY 6 PLACES.", "INCLUDED IN THE PRICE:", ["Five nights in a private villa with a pool.", "Meals by a private chef.", "The full retreat programme.", "Organised trips and transfer to the filming location.", "Professional filming.", "Two personal videos, retreat photos and videos.", "Exclusive gifts."], "NOT INCLUDED:", "Flights and transfer to the villa.\nWe will help organise the journey.", "BOOKING:", "A place is reserved with €300.\nPayment in instalments is available.", "Questions left? Write to me — I'll tell you everything personally.", "Instagram →"],
  footer: ["WITHOUT MASKS · MADEIRA 2026", "Elija Deurloo", "Instagram: @elly_love_suzai"],
}

export const translations = { ru, en } as const
export type Language = keyof typeof translations
