const ru = {
  nav: "Хочу на Мадейру",
  hero: ["МАДЕЙРА · 5–10 НОЯБРЯ 2026", "БЕЗ МАСОК", "Пять дней, в которых тебе\nне нужно быть ни для кого.", "Океан. Приватная вилла. Маленькая группа.\nИ время только для себя.", "Всего 6 мест.", "Узнать подробности ↓"],
  featuresTitle: "ЧТО ТЕБЯ ЖДЁТ",
  features: [["МАДЕЙРА", "Океан, скалы, закаты и места, которые хочется увидеть своими глазами."], ["ПРИВАТНАЯ ВИЛЛА", "Пять ночей. Бассейн, сад и вид на океан."], ["РАБОТА С СОБОЙ", "Разборы на основе методологии Сюцай.\nУвидеть связь между своими решениями,\nдействиями и результатами в жизни."], ["ПРОФЕССИОНАЛЬНАЯ СЪЁМКА", "Два персональных видео о тебе, плюс фото и видео всего путешествия."], ["ВСЕГО 6 УЧАСТНИЦ", "Маленькая группа, где есть пространство и внимание для каждой."], ["ВСЁ ОРГАНИЗОВАНО", "Питание от личного повара, программа ретрита, трансфер до локации съёмки и эксклюзивные подарки."]],
  concept: ["А какая ты, когда тебе ничего\nне нужно доказывать?", "Сильная. Правильная. Хорошая мама.\nУдобная. Успешная. Идеальная.\nТа, которая всегда справляется.", "Иногда мы так привыкаем к своим ролям, что совсем забываем, какие мы без них.", "Когда ты в последний раз принимала решение,\nне думая о том, чего от тебя ждут другие?", "«Без масок» - пять дней, чтобы отвлечься от привычных обязанностей, разобраться в своих желаниях и честно посмотреть на свою жизнь.", "НЕ ПРОСТО ОТДОХНУТЬ.\nВЕРНУТЬСЯ С ПОНИМАНИЕМ,\nЧТО ДЕЛАТЬ ДАЛЬШЕ."],
  gallery: ["КАК ЭТО БУДЕТ ОЩУЩАТЬСЯ", ["Начинать утро с прогулки и разминки у океана.", "Исследовать Мадейру.", "Говорить о том, на что обычно не хватает времени.", "Смеяться так, что болят щёки.", "Увидеть себя с другой стороны."], "Фото прошлого ретрита будет добавлено"],
  shoot: ["СЪЁМКА «БЕЗ МАСОК»", "В один из дней мы отправимся в одну из самых невероятных локаций Мадейры.", "В этот день ты сама решишь, какой хочешь себя показать. Нежной, дерзкой, сильной, уязвимой - любой. Без необходимости соответствовать чьим-то ожиданиям.", "Каждая участница получит два готовых персональных видео, а также фото и видео, снятые на протяжении всего ретрита.", "Фото Achadas da Cruz будет добавлено"],
  villa: ["НАШ ДОМ НА ПЯТЬ ДНЕЙ", "Приватная вилла только для нашей группы.\n\nБассейн. Сад. Вид на океан. И потрясающие закаты.", "Открыть галерею", "Фото"],
  hosts: [["Автор и ведущая ретрита", "Элия Дорлоу", "Коуч, тренер и официальный представитель Syucai Training Institute в Нидерландах.", "6 лет практики · Более 1000 клиентов", "Я работаю с мышлением, внутренними ограничениями, страхами и сомнениями. Помогаю разобраться, где ты сейчас, чего на самом деле хочешь и что мешает двигаться к своей цели.", "Для меня ретрит - это не только красивые места и яркие впечатления. Это глубокая внутренняя работа и конкретные действия, которые ты сможешь перенести в свою жизнь.", "Здесь будет место для честности с собой, ясности и собственных решений."], ["Видеограф ретрита", "Оля", "Профессиональный видеограф", "Оля - это тот видеограф, который горит своим делом настолько, что в момент, когда она снимает тебя, для неё существуешь только ты и твои кадры.", "Она мастерски раскрывает человека в кадре, просто непринуждённо беседуя и находя свой ключ к каждому. И те, кто ранее не нравился себе на видео, начинают смотреть на себя с восхищением.", "Твоя съёмка «Без масок» - возможность показать ту себя, которую ты, возможно, давно хотела увидеть."]],
  booking: ["MADEIRA · 5–10 НОЯБРЯ", "При бронировании до 30 сентября включительно.", "С 1 октября -", "ВСЕГО 6 МЕСТ.", "В СТОИМОСТЬ ВХОДИТ:", ["Пять ночей на приватной вилле с бассейном.", "Питание от личного повара.", "Вся программа ретрита.", "Организованные выезды и трансфер до локации съёмки.", "Профессиональная съёмка.", "Два персональных видео, фото и видео ретрита.", "Эксклюзивные подарки."], "НЕ ВХОДИТ:", "Перелёт и трансфер до виллы.\nС организацией дороги поможем.", "БРОНИРОВАНИЕ:", "Бронь места - 300 €.\nВозможна оплата частями.", "Остались вопросы? Напиши мне - расскажу всё лично.", "Instagram →"],
  footer: ["БЕЗ МАСОК · MADEIRA 2026", "Элия Дорлоу", "Instagram: @elly_love_suzai"],
}

const en = {
  nav: "I want to go to Madeira",
  hero: ["MADEIRA · NOVEMBER 5–10, 2026", "WITHOUT MASKS", "Five days when you don't have to be\nanyone for anyone else.", "Ocean. A private villa. A small group.\nAnd time just for you.", "Only 6 places.", "Learn more ↓"],
  featuresTitle: "WHAT AWAITS YOU",
  features: [["MADEIRA", "Ocean, cliffs, sunsets and places you want to see with your own eyes."], ["A PRIVATE VILLA", "Five nights. A pool, a garden and an ocean view."], ["WORKING ON YOURSELF", "Analysis based on the Syucai methodology. See the connection between your decisions, actions and the results in your life."], ["PROFESSIONAL FILMING", "Two personal videos about you, plus photos and videos from the whole journey."], ["ONLY 6 PARTICIPANTS", "A small group with space and attention for everyone."], ["EVERYTHING IS ORGANISED", "Meals by a private chef, the retreat programme, transfer to the filming location and exclusive gifts."]],
  concept: ["Who are you when you have nothing to prove?", "Strong. Proper. A good mother. Convenient. Successful. Perfect. The one who always copes.", "Sometimes we become so used to our roles that we completely forget who we are without them.", "When was the last time you made a decision without thinking about what others expect from you?", "“Without Masks” - five days to step away from your usual responsibilities, understand your desires and take an honest look at your life.", "NOT JUST TO REST.\nRETURN WITH CLARITY\nON WHAT TO DO NEXT."],
  gallery: ["HOW IT WILL FEEL", ["Starting the morning with a walk and a warm-up by the ocean.", "Exploring Madeira.", "Talking about what there is usually no time for.", "Laughing until your cheeks hurt.", "Seeing yourself from another side."], "A photo from a past retreat will be added"],
  shoot: ["“WITHOUT MASKS” FILMING", "One day we will travel to one of Madeira's most incredible locations.", "That day, you choose how you want to show yourself: tender, bold, strong, vulnerable - anything. Without having to live up to anyone's expectations.", "Each participant will receive two finished personal videos, as well as photos and videos shot throughout the retreat.", "An Achadas da Cruz photo will be added"],
  villa: ["OUR HOME FOR FIVE DAYS", "A private villa exclusively for our group.\n\nA pool. A garden. An ocean view. And breathtaking sunsets.", "Open gallery", "Photos"],
  hosts: [["Author and retreat leader", "Elija Deurloo", "Coach, trainer and official representative of Syucai Training Institute in the Netherlands.", "6 years of practice · More than 1,000 clients", "I work with mindset, inner limitations, fears and doubts. I help you understand where you are now, what you truly want and what prevents you from moving towards your goal.", "For me, a retreat is not only beautiful places and vivid impressions. It is deep inner work and concrete actions you can bring into your life.", "There will be room for honesty with yourself, clarity and your own decisions here."], ["Retreat videographer", "Olya", "Professional videographer", "Olya is the kind of videographer who is so passionate about her work that, when she films you, only you and your shots exist for her.", "She masterfully helps people open up on camera simply through relaxed conversation, finding the key to each person. Those who did not like themselves on video before begin to look at themselves with admiration.", "Your “Without Masks” shoot is an opportunity to show the version of yourself that you may have wanted to see for a long time."]],
  booking: ["MADEIRA · NOVEMBER 5–10", "For bookings by and including September 30.", "From October 1 -", "ONLY 6 PLACES.", "INCLUDED IN THE PRICE:", ["Five nights in a private villa with a pool.", "Meals by a private chef.", "The full retreat programme.", "Organised trips and transfer to the filming location.", "Professional filming.", "Two personal videos, retreat photos and videos.", "Exclusive gifts."], "NOT INCLUDED:", "Flights and transfer to the villa.\nWe will help organise the journey.", "BOOKING:", "A place is reserved with €300.\nPayment in instalments is available.", "Questions left? Write to me - I'll tell you everything personally.", "Instagram →"],
  footer: ["WITHOUT MASKS · MADEIRA 2026", "Elija Deurloo", "Instagram: @elly_love_suzai"],
}

export const translations = { ru, en } as const
export type Language = keyof typeof translations
